# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-117103223-1'

menu:
- {name: 'Writing', path: 'menu', url: 'writing.html'}
- {name: 'About', path: 'menu', url: 'about.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/gaius-qi'}
- {icon: 'twitter', link: 'https://twitter.com/gaius_qi'}
- {icon: 'weibo', link: 'https://weibo.com/2037081677'}
- {icon: 'envelope', link: 'mailto:gaius.qi@gmail.com'}
- {icon: 'rss-square', link: '/feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
